[package]
name = "physics-2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.5"
assert_approx_eq = "1.1.0"
bmp = "0.5.0"
crossbeam = "0.8.0"
bresenham = "0.1.1"
